/* The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */

function getTriangular(num){
    var sum = 0;
    for (var i = 1; i <= num; i++){
        sum += i;
    }
    return sum;
}

function countDivisors(num){
    var count = 0;
    for (var i = 1; i * i <= num; i++){
        if(num % i !== 0) {
            continue;
        }
        count += (i * i < num) ? 2 : 1;
    }
    return count;
}

var count = 0;
var triangularNum = 0;
for(var i = 1; count < 500; i++){
    triangularNum = getTriangular(i);
    count = countDivisors(triangularNum);
}

console.log(triangularNum);